#!/usr/bin/env python3
"""
Generate SQL script to update tasks from tasks.json.

This script reads tasks.json and generates a SQL UPDATE script that can be run
in Supabase SQL Editor to update all tasks in the projects table.

Usage:
    python database/python/generate_update_tasks_sql.py [--data-dir data] [--output-file database/migrations/update_tasks_from_json.sql]
"""

import json
import sys
from pathlib import Path
from typing import Dict, Any

# Ensure repository root on path
THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))


def escape_sql_string(value: Any) -> str:
    """Escape single quotes in SQL strings."""
    if value is None:
        return "NULL"
    # Convert to string if not already
    str_value = str(value)
    return str_value.replace("'", "''")


def format_json_for_sql(files: list) -> str:
    """Format files array as JSONB string for SQL."""
    if not files:
        return "'[]'::JSONB"
    # Convert to JSON string, then escape for SQL
    json_str = json.dumps(files, ensure_ascii=False)
    escaped = escape_sql_string(json_str)
    return f"'{escaped}'::JSONB"


def format_date_for_sql(date_str: str) -> str:
    """Format date string for SQL."""
    if not date_str:
        return "NULL::DATE"
    return f"'{date_str}'::DATE"


def generate_sql_from_tasks(tasks: list[Dict[str, Any]]) -> str:
    """Generate SQL UPDATE script from tasks list."""
    
    sql_parts = [
        "-- Migration: Update tasks from tasks.json data",
        "-- Description: Updates existing projects/tasks with new data from tasks.json",
        "-- This script updates tasks by their 'name' field, preserving database IDs",
        "--",
        "-- Generated by: database/python/generate_update_tasks_sql.py",
        "--",
        "",
        "WITH task_updates AS (",
    ]
    
    # Generate UNION ALL blocks for each task
    union_parts = []
    for task in tasks:
        name = task.get("name", "")
        if not name:
            continue
        
        title = task.get("title", "")
        label = task.get("label", "")
        description = task.get("description", "")
        files = task.get("files", [])
        code_start_date = task.get("code_start_date", "")
        voting_start_date = task.get("voting_start_date", "")
        voting_end_date = task.get("voting_end_date", "")
        
        # Format values (convert to string for SQL)
        name_sql = f"'{escape_sql_string(name)}'::VARCHAR"
        title_sql = f"'{escape_sql_string(title)}'::VARCHAR" if title is not None else "NULL::VARCHAR"
        label_sql = f"'{escape_sql_string(label)}'::VARCHAR" if label else "NULL::VARCHAR"
        description_sql = f"'{escape_sql_string(description)}'::TEXT" if description else "NULL::TEXT"
        files_sql = format_json_for_sql(files)
        code_start_sql = format_date_for_sql(code_start_date)
        voting_start_sql = format_date_for_sql(voting_start_date)
        voting_end_sql = format_date_for_sql(voting_end_date)
        
        union_parts.append(
            f"  SELECT\n"
            f"    {name_sql} AS name,\n"
            f"    {title_sql} AS title,\n"
            f"    {label_sql} AS label,\n"
            f"    {description_sql} AS description,\n"
            f"    {files_sql} AS files,\n"
            f"    {code_start_sql} AS code_start_date,\n"
            f"    {voting_start_sql} AS voting_start_date,\n"
            f"    {voting_end_sql} AS voting_end_date"
        )
    
    # Join with UNION ALL
    sql_parts.append(" UNION ALL\n".join(union_parts))
    sql_parts.append(")")
    
    # Add UPDATE statement
    sql_parts.extend([
        "",
        "UPDATE projects p",
        "SET",
        "  title = tu.title,",
        "  label = tu.label,",
        "  description = tu.description,",
        "  files = tu.files,",
        "  code_start_date = tu.code_start_date,",
        "  voting_start_date = tu.voting_start_date,",
        "  voting_end_date = tu.voting_end_date,",
        "  updated_at = NOW()",
        "FROM task_updates tu",
        "WHERE p.name = tu.name;",
        "",
        "-- Verify updates (optional - comment out if not needed)",
        "-- SELECT",
        "--   name,",
        "--   title,",
        "--   label,",
        "--   LEFT(description, 50) || '...' AS description_preview,",
        "--   code_start_date,",
        "--   voting_start_date,",
        "--   voting_end_date,",
        "--   updated_at",
        "-- FROM projects",
        "-- WHERE name IN (SELECT name FROM task_updates)",
        "-- ORDER BY name;",
    ])
    
    return "\n".join(sql_parts)


def main() -> int:
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Generate SQL script to update tasks from tasks.json"
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default="data",
        help="Directory containing tasks.json file (default: 'data')"
    )
    parser.add_argument(
        "--output-file",
        type=str,
        default="database/migrations/update_tasks_from_json.sql",
        help="Output SQL file path (default: 'database/migrations/update_tasks_from_json.sql')"
    )
    args = parser.parse_args()
    
    # Load tasks.json
    data_path = REPO_ROOT / args.data_dir / "tasks.json"
    if not data_path.exists():
        print(f"❌ Not found: {data_path}")
        return 1
    
    try:
        payload = json.loads(data_path.read_text(encoding="utf-8"))
        tasks = payload.get("tasks", [])
        
        if not tasks:
            print("⚠️  No tasks found in tasks.json")
            return 1
        
        # Generate SQL
        sql = generate_sql_from_tasks(tasks)
        
        # Write to output file
        output_path = REPO_ROOT / args.output_file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(sql, encoding="utf-8")
        
        print(f"✅ Generated SQL script: {output_path}")
        print(f"   Updated {len(tasks)} tasks")
        print(f"   Run this script in Supabase SQL Editor to update all tasks")
        return 0
        
    except Exception as e:
        print(f"❌ Error generating SQL: {e}")
        import traceback
        traceback.print_exc()
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
