-- Migration: Update tasks from tasks.json data
-- Description: Updates existing projects/tasks with new data from tasks.json
-- This script updates tasks by their 'name' field, preserving database IDs
--
-- Generated by: database/python/generate_update_tasks_sql.py
--

WITH task_updates AS (
  SELECT
    'ai_opponent'::VARCHAR AS name,
    'AI Opponent'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create any game where the player competes against an AI opponent rather than another human. The AI should make decisions based on the current game state so it feels like an intentional opponent, even if its strategy is lightweight.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'asteroids'::VARCHAR AS name,
    'Asteroids'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a 2D space shooter where the player must avoid floating asteroids. The player rotates a ship, thrusts to gain momentum, and fires bullets while asteroids drift through space and wrap around the screen edges.</p><p>Shooting an asteroid breaks it into smaller asteroids until the smallest size is destroyed, so the screen gets more chaotic before it gets safer. The player avoids collisions while clearing waves that get faster or denser, and the run tracks score and lives so it feels like a classic arcade loop.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'battleship'::VARCHAR AS name,
    'Battleship'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a game where ships are placed on a hidden grid and the player fires shots by selecting coordinates. Each shot should reveal hit or miss and remain marked so the player can track previous guesses.</p><p>The game should support one-player against an AI opponent (and optionally two-player locally). The AI does not need to be sophisticated, but should be able to make valid moves on its own. Track ship health so a ship is “sunk” when all its cells are hit, and end the game when all ships are sunk. The UI should show shot history clearly and communicate hit/miss/sunk feedback instantly after each move.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'blackjack'::VARCHAR AS name,
    'Blackjack'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a card game where the player competes against a dealer to reach a score of 21. Cards are dealt from a shuffled deck, and each hand’s value is the sum of card ranks with Aces counting as 1 or 11, depending on what helps the hand most.</p><p>The player chooses to Hit (take another card) or Stand (end their turn), trying to get closer to 21 without going over. After the player stands, the dealer reveals their hidden card and draws until reaching at least 17, then totals are compared to decide win/lose/push.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'breakout'::VARCHAR AS name,
    'Breakout'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a paddle-and-ball arcade game where the player attempts to break all bricks on the screen. The player controls a paddle along the bottom of the screen and keeps the ball from falling off the bottom edge while aiming bounces toward bricks near the top.</p><p>The ball reflects off the walls and the paddle, and each time it hits a brick the brick disappears. The goal is to clear all bricks (or as many as possible) before losing all lives, with score increasing as bricks are destroyed.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'bullet_hell_survival'::VARCHAR AS name,
    'Bullet Hell Survival'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a top-down survival game where enemies spawn continuously and must be defeated or avoided by the player. The player’s role is movement and positioning while attacks fire automatically on a cooldown.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'checkers'::VARCHAR AS name,
    'Checkers'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>the classic board game on an 8×8 board where players move pieces diagonally and take turns to capture opponent pieces. A normal piece moves forward one square into an empty space, and captures by jumping over an adjacent opponent piece into the empty square beyond it.</p><p>The game should support one-player against an AI opponent (and optionally two-player locally). The AI does not need to be sophisticated, but should be able to make valid moves on its own. Require captures when available, remove captured pieces immediately, and promote a piece to a king when it reaches the far row so it can move backward too. The game ends when a player has no legal moves, and the UI should highlight legal moves and clearly show whose turn it is.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'chess'::VARCHAR AS name,
    'Chess'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a classic 8×8 strategy board game where players alternate turns moving pieces with distinct movement rules (pawns, knights, bishops, rooks, queen, and king), aiming to trap the enemy king. Moves can capture opponent pieces, changing the position and available tactics each turn.</p><p>The key rule is check and checkmate: the game ends when the king is attacked and has no legal escape. A web version should make turns readable, show legal moves clearly, and indicate check/checkmate/stalemate states in a way that’s easy to understand while playing.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'connect_four'::VARCHAR AS name,
    'Connect Four'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a vertical grid game where players drop discs into columns to connect four discs in a row. On a turn, the player selects a column and the disc falls to the lowest empty slot as if pulled by gravity.</p><p>The game should support one-player against an AI opponent (and optionally two-player locally). The AI does not need to be sophisticated, but should be able to make valid moves on its own. The first player to connect four of their discs in a single line—horizontal, vertical, or diagonal—wins the round. If the grid fills without a four-in-a-row, it’s a draw, and the UI should make turn order and win states very obvious.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'cookie_clicker'::VARCHAR AS name,
    'Cookie Clicker'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create an incremental clicker game where clicking produces currency and that currency buys generators that automatically produce more currency over time. The experience is about watching numbers grow and making upgrades that accelerate growth.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'crossword'::VARCHAR AS name,
    'Crossword Puzzle'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a word puzzle on a grid of intersecting across and down answers. The player fills letters into blank cells so that each entry matches its clue, and intersecting words constrain each other.</p><p>Typical play involves selecting a clue, typing letters into the active entry, and navigating with arrow keys or clicks between cells and words. A web version can automatically create a puzzle, highlight the active word in the grid, and allow the user to check whether their board is correct/incorrect.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'deck_builder_combat'::VARCHAR AS name,
    'Deck Builder'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a turn-based card combat game where the player draws a hand of cards each turn and plays cards to attack, block, heal, or apply effects. The goal of the player is to defeat another player who is drawing cards from the same hand</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'doodle_jump'::VARCHAR AS name,
    'Doodle Jump'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a vertical endless platformer where the character automatically jumps on platforms and tries to climb as high as possible without falling. The player only controls horizontal movement to land on platforms and keep climbing while the camera follows upward.</p><p>Platforms are generated procedurally above the player and recycled below, so the level can continue indefinitely. The run ends when the character falls below the bottom of the screen, and score is typically the highest height reached, encouraging repeated attempts to beat a best run.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'endless_arcade'::VARCHAR AS name,
    'Endless'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Design a game that can run indefinitely, where the goal is always to beat a previous best score. The player should never truly “finish” the game; instead the challenge continuously ramps.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'fighting_game'::VARCHAR AS name,
    'Fighting Game'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create any game where the player needs to fight against another opponent. Each player has a health bar, and the game ends when one of the players runs out of health. The player with the most health wins the game.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'frogger'::VARCHAR AS name,
    'Frogger'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a lane-crossing action game where the player moves a character one step per key press across roads and rivers to reach safety at the top of the screen.</p><p>Cars move in lanes and collisions cost a life, while river sections require the player to ride moving platforms like logs or turtles to avoid falling into water. A round usually includes a timer and multiple successful crossings, with later rounds increasing speed and traffic density.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'gravity_shift'::VARCHAR AS name,
    'Gravity Change'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where gravity direction can change, either by player control or by moving between areas with different gravity.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'hangman'::VARCHAR AS name,
    'Hangman'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a word guessing game where the player tries to uncover a secret word by guessing letters. Correct guesses fill in the blanks wherever the letter appears in the word.</p><p>Incorrect guesses consume a limited number of attempts and advance a simple visual mistake counter until the player either completes the word or runs out of tries. The UI should show used letters and provide a quick restart so it feels snappy to replay.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'interactive_story'::VARCHAR AS name,
    'Interactive Story'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a branching narrative where the user reads scenes and makes choices that influence what happens next.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'jam_theme'::VARCHAR AS name,
    'Jam-themed Game'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>In the spirit of VibeJam, create a game where <strong>jam</strong> is central to the theme or mechanics, whether that’s fruit jam, music jam, or game jam.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'mancala'::VARCHAR AS name,
    'Mancala'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a board game with pits and a store for each player. On your turn, you pick a pit on your side and distribute its stones one-by-one into subsequent pits around the board.</p><p>Depending on where the last stone lands, you may get an extra turn or capture stones, and the game ends when one side’s pits are empty. Remaining stones are collected and the higher store total wins, so the strategy is about planning where your final stone lands and how you starve your opponent of moves.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'match_three'::VARCHAR AS name,
    'Match-3 Puzzle'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a puzzle game on a grid of colored tiles, where the player swaps adjacent tiles to create lines of three or more matching tiles (e.g. Candy Crush). If a swap creates a line of three or more matching tiles, those tiles clear and new tiles fall in from above.</p><p>Allow chain reactions when new falls create additional matches, and track score based on cleared tiles and combos. The UI should animate swaps and clears clearly, and prevent swaps that don’t result in a match.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'maze'::VARCHAR AS name,
    'Maze Game'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a maze navigation game where the player must reach an exit through tricky mazes. The goal is typically to find the way out.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'memory'::VARCHAR AS name,
    'Memory'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where remembering past information is a core mechanic of the game.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'memory_match'::VARCHAR AS name,
    'Memory Matching'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a concentration game where players flip cards to try and find matching pairs. The player flips two cards per turn, trying to find matching pairs by remembering previously seen card faces.</p><p>If the two revealed cards match they stay face-up, and if they don’t match they flip back after a short delay, giving the player a moment to memorize them. The game ends when all pairs are found, and you can show moves or time as the “score” to encourage replay. The game should support one-player against an AI opponent (and optionally two-player locally). The AI does not need to be sophisticated, but should be able to make valid moves on its own.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'minesweeper'::VARCHAR AS name,
    'Minesweeper'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a logic puzzle where a player must click on a grid of hidden tiles, avoiding those containing mines. Clicking a tile reveals either a mine (which ends the game) or a number showing how many adjacent tiles contain mines.</p><p>The player uses the numbers to deduce where mines are and flags suspected mines, trying to reveal all non-mine tiles to win. Revealing a zero expands into a region of safe tiles, which makes deduction and exploration feel satisfying.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'pacman'::VARCHAR AS name,
    'Pac-Man'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a top-down 2D maze chase game where the player collects pellets and avoids enemies. The player navigates corridors collecting pellets while avoiding enemies that move through the maze.</p><p>Enemies follow simple behavior patterns like chasing the player, enemies to corners, or making randomized decisions at intersections. Power pellets temporarily make enemies vulnerable so the player can eat them for bonus points before they respawn, and the level ends when all pellets are cleared or the player loses all lives.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'password_game'::VARCHAR AS name,
    'Password Game'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a puzzle where the player must type a password that satisfies a growing list of rules. Rules are revealed progressively, and the password must satisfy all rules simultaneously as they stack up.</p><p>The fun comes from adjusting the password as new constraints appear, while the UI shows a live pass/fail indicator for every rule and explains what is missing. Players “win” when all rules are satisfied at once, making it feel like a logic juggling act.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'pinball'::VARCHAR AS name,
    'Pinball'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a retro arcade game where a ball moves under gravity and bounces off walls and bumpers, awarding points when it hits targets. The player controls two flippers near the bottom to keep the ball in play.</p><p>Increase score through bumper hits and target combinations, and end the run when the ball falls out of bounds, with multiple balls/lives per game. The UI should show score and remaining balls clearly, and the physics should feel responsive and consistent.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'platformer'::VARCHAR AS name,
    'Platformer'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a platformer game, where the player must run, jump, or user other movement across platforms to reach a goal.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'pong'::VARCHAR AS name,
    'Pong'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a two-paddle ball game where the ball bounces between paddles and the top/bottom walls. A player scores when the ball passes the opponent’s paddle.</p><p>The paddles move up and down, and after each point the ball resets and serves again, continuing until a target score is reached. The appeal is simple but satisfying physics and a clear scoreboard that makes the duel feel competitive. The second player can either be another human or an AI.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'puzzle'::VARCHAR AS name,
    'Puzzle Game'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where users must solve puzzles in order to beat the game or levels in the game.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'reaction'::VARCHAR AS name,
    'Reaction Test'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game that relies on users having good "reaction time": how well they can respond to new inputs on the screen</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'rps'::VARCHAR AS name,
    'Rock-Paper-Scissors'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a classic game where players choose Rock, Paper, or Scissors, then reveal simultaneously and apply the standard rules (Rock beats Scissors, Scissors beats Paper, Paper beats Rock) to decide the winner. The game can be played either against an AI or as local two-player on the same device.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'scale'::VARCHAR AS name,
    'Growing or Shrinking'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where a core mechanic involves the main character growing or shrinking in size</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'simon'::VARCHAR AS name,
    'Simon'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a memory game where the game shows a sequence of highlighted buttons (colors/shapes) and the player must repeat the sequence in the same order.</p><p>Each successful round adds one more step, making the sequence longer and harder to remember. A purely visual version still works well by using strong highlights and timing, and the player’s score is typically the longest sequence completed before making a mistake.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'slots'::VARCHAR AS name,
    'Slot Machine'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a visual luck game where the player spends coins to spin multiple reels that stop on random symbols. After each spin, evaluate paylines and award payouts based on matching symbol combinations.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'snake'::VARCHAR AS name,
    'Snake'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a grid-based arcade game where a snake aims to become as big as possible by eating food. The snake moves continuously in the current direction and the player steers it with arrow keys or WASD. Each tick advances the snake by one cell, so the path you choose matters.</p><p>Food appears on empty cells, and eating it grows the snake and increases score, making movement progressively harder. The game ends when the snake hits the wall or itself, and a good version makes restarting fast and keeps a best score to encourage “one more try.”</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'space'::VARCHAR AS name,
    'Space'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Build any game set in outer space.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'space_invaders'::VARCHAR AS name,
    'Space Invaders'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a fixed-screen shooter where the player controls a ship at the bottom moving left/right and firing upward at rows of marching aliens.</p><p>Aliens sweep side-to-side, reversing direction at edges and stepping downward over time, while occasionally firing back. The player wins a wave by eliminating all aliens and loses if hit too many times or if the aliens reach the bottom, and successive waves should feel faster and more intense.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'sudoku'::VARCHAR AS name,
    'Sudoku'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a classic puzzle game with a 9×9 grid where the player fills empty cells with digits 1–9 so that every row, every column, and each 3×3 subgrid contains all digits exactly once. Start from a valid puzzle with some cells pre-filled and locked so they cannot be edited.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'swap'::VARCHAR AS name,
    'Swapped Rules'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where a core rule or interaction is swapped, reverse or unexpected from the typical.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'tabletop'::VARCHAR AS name,
    'Tabletop Game'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a web version of an existing board or card game that can be played as a single player, against an AI, or with another player</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'tetris'::VARCHAR AS name,
    'Tetris'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a falling-block puzzle game where tetromino pieces descend from the top of a vertical board and the player moves and rotates them to fit together.</p><p>Completing a full horizontal line clears it and drops everything above, rewarding points and opening space, and the game speeds up over time to increase pressure. The run ends when the stack reaches the top and new pieces can’t spawn, making it a battle for efficiency and calm decision-making.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'tic_tac_toe'::VARCHAR AS name,
    'Tic-Tac-Toe'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a 3×3 grid game where players take turns placing X and O by clicking an empty cell, aiming to make three in a row. Once placed, the symbol stays, so each move changes the remaining possibilities.</p><p>The round ends when someone makes three in a row (row/column/diagonal) or the grid fills with no winner. A good version shows whose turn it is, highlights the winning line, and makes restarting instant so players can run it back.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'time_loop'::VARCHAR AS name,
    'Time Loop'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where a core mechanic involves the player repeating the same sequence of events over and over.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'time_pressure'::VARCHAR AS name,
    'Speed'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game where the core difficulty relies on the time taken to beat the game.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'tower_defense'::VARCHAR AS name,
    'Tower Defense'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a tower defense game where enemies follow a path and the player places towers to stop them before they reach the base.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'two_zero_four_eight'::VARCHAR AS name,
    '2048'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a sliding tile puzzle on a 4×4 grid where the player swipes or presses arrow keys to slide all tiles in one direction, aiming to merge tiles into larger numbers. Tiles compress toward the edge until blocked by another tile or the border.</p><p>When two equal-number tiles collide during a move, they merge into a single tile with double the value, and then a new tile (2 or 4) appears in an empty cell. The puzzle ends when no moves remain, and the score grows based on merges as the player aims for bigger and bigger numbers.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'typing_test'::VARCHAR AS name,
    'Typing Speed'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a typing game where the user types a given text passage and the app measures typing speed in real time. As the user types, keystrokes are tracked to calculate words per minute (WPM) and accuracy, and incorrect characters are visually highlighted so mistakes are immediately clear.</p><p>When the test ends, display a results screen showing statistics for the users to improve on, such as WPM, accuracy percentage, total characters typed, and error count.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'underwater'::VARCHAR AS name,
    'Water Game'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a game either set under or near water or with a core mechanic related to water</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'virtual_pet'::VARCHAR AS name,
    'Virtual Pet'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a virtual pet game where the player takes care of a pet that lives in a small UI panel and has needs like Hunger, Happiness, and Energy that decay over time. The player cares for the pet by choosing actions that raise these meters.</p><p>Feeding, playing, cleaning, and sleeping change the pet’s state, and ignoring needs makes the pet look sad or sick and can lead to a game-over.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'whack_a_mole'::VARCHAR AS name,
    'Whack-a-Mole'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a reaction game where targets pop up in random holes for a short time and the player scores by clicking/tapping them before they disappear.</p><p>Make the game run on a timer, increase difficulty by speeding up spawns, and track score and accuracy. The UI should give immediate feedback for hits and misses and make restarting instant for quick replays.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'wordle'::VARCHAR AS name,
    'Wordle'::VARCHAR AS title,
    'replication'::VARCHAR AS label,
    '<p>a word guessing game where the player has a limited number of attempts to guess a hidden word. Each attempt is typed into a row and submitted as a full guess.</p><p>After submission, each letter tile is colored to show whether the letter is correct and in the correct position, correct but in a different position, or not in the word at all. The player uses that feedback to narrow the answer until they guess correctly or run out of attempts, and the UI should make the feedback easy to read at a glance.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date UNION ALL
  SELECT
    'zen_garden'::VARCHAR AS name,
    'Zen Garden'::VARCHAR AS title,
    'open-ended'::VARCHAR AS label,
    '<p>Create a relaxing game where players casually place objects and watch a peaceful scene grow over time, with no goals, pressure, or winning.</p>'::TEXT AS description,
    '[{"name": "index.html", "content": "data/code_files/blank_site/index.html", "language": "html"}, {"name": "styles.css", "content": "data/code_files/blank_site/styles.css", "language": "css"}, {"name": "frontend.js", "content": "data/code_files/blank_site/frontend.js", "language": "javascript"}]'::JSONB AS files,
    '2025-01-01'::DATE AS code_start_date,
    '2027-02-08'::DATE AS voting_start_date,
    '2050-02-15'::DATE AS voting_end_date
)

UPDATE projects p
SET
  title = tu.title,
  label = tu.label,
  description = tu.description,
  files = tu.files,
  code_start_date = tu.code_start_date,
  voting_start_date = tu.voting_start_date,
  voting_end_date = tu.voting_end_date,
  updated_at = NOW()
FROM task_updates tu
WHERE p.name = tu.name;

-- Verify updates (optional - comment out if not needed)
-- SELECT
--   name,
--   title,
--   label,
--   LEFT(description, 50) || '...' AS description_preview,
--   code_start_date,
--   voting_start_date,
--   voting_end_date,
--   updated_at
-- FROM projects
-- WHERE name IN (SELECT name FROM task_updates)
-- ORDER BY name;