#!/usr/bin/env node

/**
 * Sync environment variables from backend/.env to interface/.env.local
 * This ensures both frontend and backend use the same configuration
 */

const fs = require('fs');
const path = require('path');

// Paths
const backendEnvPath = path.join(__dirname, '../backend/.env');
const frontendEnvPath = path.join(__dirname, '../interface/.env.local');

// Check if backend/.env exists
if (!fs.existsSync(backendEnvPath)) {
  console.error('❌ Error: backend/.env not found!');
  process.exit(1);
}

// Read backend .env file
const backendEnvContent = fs.readFileSync(backendEnvPath, 'utf8');

// Parse environment variables
const envVars = {};
backendEnvContent.split('\n').forEach(line => {
  line = line.trim();
  
  // Skip comments and empty lines
  if (!line || line.startsWith('#')) return;
  
  const [key, ...valueParts] = line.split('=');
  if (key && valueParts.length > 0) {
    const value = valueParts.join('=').trim();
    envVars[key.trim()] = value;
  }
});

// Map backend variables to frontend variables
const frontendEnvVars = {
  NEXT_PUBLIC_BACKEND_URL: envVars.BACKEND_URL || 'http://localhost:4828',
  NEXT_PUBLIC_BACKEND_WS_URL: envVars.BACKEND_WS_URL || 'ws://localhost:4828',
  NEXT_PUBLIC_FRONTEND_URL: envVars.FRONTEND_URL || 'http://localhost:4827',
  NEXT_PUBLIC_DEFAULT_BACKEND_PORT: envVars.DEFAULT_BACKEND_PORT || '5000',
  NEXT_PUBLIC_SHOW_PUBLIC_TESTS_ONLY: envVars.SHOW_PUBLIC_TESTS_ONLY || 'true',
  USE_LOCAL_EXECUTION: envVars.USE_LOCAL_EXECUTION || 'false',
};

// Create frontend .env.local content
const frontendEnvContent = `# Auto-generated from backend/.env
# Do not edit this file directly - edit backend/.env and run 'npm run sync-env'

# Backend API Configuration
NEXT_PUBLIC_BACKEND_URL=${frontendEnvVars.NEXT_PUBLIC_BACKEND_URL}
NEXT_PUBLIC_BACKEND_WS_URL=${frontendEnvVars.NEXT_PUBLIC_BACKEND_WS_URL}

# Frontend Configuration  
NEXT_PUBLIC_FRONTEND_URL=${frontendEnvVars.NEXT_PUBLIC_FRONTEND_URL}

# Default backend port for user code execution
NEXT_PUBLIC_DEFAULT_BACKEND_PORT=${frontendEnvVars.NEXT_PUBLIC_DEFAULT_BACKEND_PORT}

# Test Cases Configuration
# Set to 'false' to show ALL test cases (including private/hidden tests)
# Set to 'true' (or omit) to show only public test cases
NEXT_PUBLIC_SHOW_PUBLIC_TESTS_ONLY=${frontendEnvVars.NEXT_PUBLIC_SHOW_PUBLIC_TESTS_ONLY}
`;

// Write to frontend .env.local
fs.writeFileSync(frontendEnvPath, frontendEnvContent);

Object.entries(frontendEnvVars).forEach(([key, value]) => {
});

